FROM centos:8
RUN mkdir /opt/oracle && \
    groupadd -r oracle && \
    useradd --no-log-init -r -g oracle oracle && \
    useradd -G oracle oinstall && \
    chown oracle:oinstall /opt/oracle && chmod 774 /opt/oracle
WORKDIR /opt/oracle
COPY oracle-database-xe-18c-1.0-1.x86_64.rpm /opt/oracle
# download dependencies
RUN curl -o oracle-database-preinstall-18c-1.0-1.el7.x86_64.rpm \
    https://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/getPackage/oracle-database-preinstall-18c-1.0-1.el7.x86_64.rpm && \
    curl -o compat-libstdc++-33-3.2.3-72.el7.x86_64.rpm http://mirror.centos.org/centos/7/os/x86_64/Packages/compat-libstdc++-33-3.2.3-72.el7.x86_64.rpm && \
    curl -o compat-libcap1-1.10-7.el7.x86_64.rpm http://mirror.centos.org/centos/7/os/x86_64/Packages/compat-libcap1-1.10-7.el7.x86_64.rpm

# install dependencies
RUN yum -y localinstall compat-libstdc++-33-3.2.3-72.el7.x86_64.rpm
RUN yum -y localinstall compat-libcap1-1.10-7.el7.x86_64.rpm
# install oracle 
RUN yum -y localinstall oracle-database*18c* && \
    /etc/init.d/oracle-xe-18c configure
